[package]
name = "rustcomb"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.0.16"
clap = { version = "4.5.31", features = ["derive"] }
criterion = { version = "0.5.1", features = ["html_reports"] }
num_cpus = "1.16.0"
predicates = "3.1.3"
rayon = "1.10.0"
regex = "1.11.1"
threadpool = "1.8.1"
walkdir = "2.5.0"
wild = "2.2.1"

[[bench]]
name = "my_benchmark"
harness = false
