[package]
name = "rustcomb"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.0.16"
clap = { version = "4.5.31", features = ["derive"] }
predicates = "3.1.3"
regex = "1.11.1"
threadpool = "1.8.1"
wild = "2.2.1"
